- name: EC2 Instances & R53 Records creation
  hosts: local
  connection: local
  vars:
    instance_type: t3.micro
    security_group: sg-03c4d065bf7f7f94d
    image_id: ami-09c813fb71547fc4f
    domain: bloombear.fun
  tasks: 

  - name: Creating EC2 Instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ security_group }}"
      image_id: "{{ image_id }}"
    register: output
    loop: "{{ instances }}"

  - name: print ec2 output
    ansible.builtin.debug:
      msg: "{{item.item}}"
    loop: "{{output.results}}"

  # - name: Creating or Updating R53 Records
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{domain}}"
  #     record: "{{item.item}}.{{domain}}"
  #     type: A
  #     ttl: 1
  #     value: #next
  #     wait: true
    
