- name: "loop practice"
  hosts: "local"
  connection: "local"
  become: "yes"
  tasks: 
  - name: "printing the names"
    ansible.builtin.debug:
      msg: "Hello {{item}}"
    loop: ["vinay", "siva", "rahul"]
      
