- name: Configuring shipping server
  hosts: shipping
  become: yes
  tasks:
  - name: install mysql python libraries
    ansible.builtin.pip:
      executable: pip3.9
      name: "{{ item }}"
    loop:
      - cryptography
      - PyMySQL

  # installing maven
  - name: installing maven package
    ansible.builtin.package: 
      name: maven
      state: present
  
  # Creating roboshop system user
  # idempotent unlike the normal shell command
  - name: creating roboshop system user
    ansible.builtin.user:
      name: roboshop
      comment: RoboShop System user
      system: true
      shell: /sbin/nologin
      home: /app

  # deleting the app directory
  - name: deleting the app directory
    ansible.builtin.file:
      path: /app
      state: absent
  
  # creating the app directory
  - name: creating the app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  # deleting shipping code file in tmp directory
  - name: deleting the shipping code file in tmp directory
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  # downloading shipping application
  - name: downloading shipping application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  # unzipping the shipping file
  - name: extracting the shipping file into app directory
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  # installing the dependencies
  - name: installing the dependencies
    ansible.builtin.command: mvn clean package 
    args:
      chdir: /app

  # moving the jar file
  - name: moving the jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  # copying shipping service file into /etc/systemd/system/shipping.service
  - name: copying shipping service file
    ansible.builtin.copy:
      src: ./shipping.service
      dest: /etc/systemd/system/shipping.service

  # loading the shipping data into mysql server
  - name: import shipping data into mysql
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: mysql.bloombear.fun
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

  # daemon reload, enabling service and startin it
  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: shipping
      enabled: true
      state: started
      daemon_reload: true